spring:
  application:
    name: Spring-Reactive-Data-Redis

  # Redis DB configuration
  redis:
    host: localhost
    port: 6379
    database: 4
    password: 123456

# Server configuration
server:
  port: 8080
  error:
    include-message: always

# Logging settings
logging:
  level:
    root: INFO
    com.recyclable: DEBUG
    org.springframework.data.redis: DEBUG